name: binder
channels:
  - conda-forge
dependencies:
  - python=3.13
  - jupyterlab
  - jupytext
  - jupyterlab-myst
  - napari
  - pyqt
  - jupyter-book<2
  - websockify
  - pip
  - pip:
    - jupyter-remote-desktop-proxy
